<a href="https://colab.research.google.com/github/SaiDhanyaa/WORK-OUTS/blob/main/FEATURE_ENGINEERING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Univariate Feature Selection**

In [1]:
# Feature Extraction with Univariate Statistical Tests (Chi-squared for classification)
from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [2]:
# load data
filename = '/content/pima-indians-diabetes.csv'

In [3]:
## it has no column names. assingning the column names..
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = read_csv(filename, names=names)

In [4]:
data.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [5]:
### splitting the x and y variable...
array = data.values
X = array[:,0:8]
Y = array[:,8]

In [7]:
# feature extraction.... we are using SelecetKBest package from  the scikitlearn..
model = SelectKBest(score_func=chi2, k=4)
fit = model.fit(X, Y)

In [8]:
# summarize scores
set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)

[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]


In [ ]:
#For regression: f_regression, mutual_info_regression
#For classification: chi2, f_classif, mutual_info_classif

## **Recursive Feature Elimination**

In [9]:
# Feature Extraction with RFE
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
# load data
filename = '/content/pima-indians-diabetes.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]
# feature extraction
model = LogisticRegression(max_iter=400)
rfe = RFE(model, 3)
fit = rfe.fit(X, Y)

In [10]:
#Num Features: 
fit.n_features_

3

In [11]:
#Selected Features:
fit.support_

array([ True, False, False, False, False,  True,  True, False])

In [12]:
# Feature Ranking:
fit.ranking_

array([1, 2, 4, 6, 5, 1, 1, 3])

In [ ]:
## compare it with above array which is the top feature numbered as 1 and true
#['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

# **# Feature Importance with Extra Trees Classifier**

In [14]:
# Feature Importance with Extra Trees Classifier
from pandas import read_csv
from sklearn.tree import  DecisionTreeClassifier
# load data
filename = '/content/pima-indians-diabetes.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]
# feature extraction
model = DecisionTreeClassifier()
model.fit(X, Y)
print(model.feature_importances_)

[0.057 0.307 0.088 0.018 0.038 0.236 0.142 0.114]
